name: Build and deploy Node.js backend to Azure Web App - better-me

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install backend dependencies
        run: npm install
        working-directory: SAAS-backend

      - name: Upload backend artifact (includes full backend)
        uses: actions/upload-artifact@v4
        with:
          name: node-backend
          path: SAAS-backend/**
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-backend

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2A6AA3CC5C3C4DA68847EDCB2A982993 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9BD32F2988BB41068DD1BFF5D76CA39E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6D42904CEB8A4F9E95FB98643610F0F7 }}

      - name: Deploy backend to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: "better-me"
          package: .
